---
title: "R Notebook"
output: html_notebook
---

### Scree and elbow plots to determine clusters

```{r}
scree_selection <- data_cluster[,-1]          

# scree parameters
scree_wss <- 0                 # initialize total within sum of squares error
scree_k   <- 5                 # number of clusters to cycle
scree_ns <- 10                 # number of random starts to cycle

# For 1 to 15 cluster centers
for (i in 1:scree_k) {
  km_out <- kmeans(scree_selection, centers = i, nstart = scree_ns)
  # Save total within sum of squares to wss variable
  scree_wss[i] <- km_out$tot.withinss
}

# Quickplot of total within sum of squares vs. number of clusters
plot(1:scree_k, scree_wss, type = "b", 
     xlab = "Number of Clusters", 
     ylab = "Within groups sum of squares")

# clean up environment
rm(i, scree_selection, scree_k, scree_ns, scree_wss, km_out)
```

### Run clustering algorithm

```{r}
# set random seed for reproducibility
set.seed(1337)

# run k-means with 3 centers and 20 starts
k_output <- kmeans(data_cluster_elite[,-1], 3, nstart = 20)

```

### Merge clusters to data

```{r}
data_cluster_elite$cluster <- k_output$cluster
```

### Calculate cluster means

```{r}
# calculate cluster means as seperate columns and bind them together
clusters <-
  cbind(
data_cluster_elite[,-1] %>% 
  subset(cluster == 1) %>% 
  colMeans(),
data_cluster_elite[,-1] %>% 
  subset(cluster == 2) %>% 
  colMeans(),
data_cluster_elite[,-1] %>% 
  subset(cluster == 3) %>% 
  colMeans()
)

# set cluster number as columnnames
colnames(clusters) = clusters["cluster",]
```

### Plot cluster heatmap

```{r}
# remove row names cluster and melt data
plotdata_h <-clusters[-which(rownames(clusters) %in% c("cluster")), ] %>% 
  melt()

# remove columns to standardised names
colnames(plotdata_h) <- c("Var1", "Var2", "value")

# plot heatmap
ggplot(plotdata_h, aes(Var2, Var1)) + geom_tile(aes(fill = value), colour = "white") + scale_fill_gradient(low = "white", high = "#01B8AA") + theme(legend.position="none", axis.line=element_blank(), axis.ticks=element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank())
```